server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: updating-microservices
          uri: https://github.com/AlejBravo/Bravo-ClientService.git
          search-paths: config-data
  application:
    name: config-service